config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
      sessions: 'admins/sessions'
  }


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'inicio#index'
  get 'inicio', to: 'inicio#index', as:'inicio'

  get 'informeestudiante/', to: 'informe_estudiantes#index', as: 'informeestudiantes'
  get 'informeestudiante/nuevo/', to: 'informe_estudiantes#nuevo', as: 'nuevo_informe_estudiante'
  #get 'informeestudiante/:id',to: 'informe_estudiantes#mostrar', as: 'informeestudiante'

  get 'informeestudiante/:id/estudiante',to: 'informe_estudiantes#informes_por_estudiante', as: 'informeporestudiante'

  get 'informeestudiante/:id/editar', to: 'informe_estudiantes#editar', as: 'editar_informe_estudiante'
  post 'informeestudiante/', to: 'informe_estudiantes#crear', as: 'agregar_informe_estudiante'
  put 'informeestudiante/:id' , to: 'informe_estudiantes#update'
  patch 'informeestudiante/:id' ,to: 'informe_estudiantes#update'
  delete 'informeestudiante/:id', to: 'informe_estudiantes#eliminar'



  get 'preguntas/', to: 'preguntas#index', as: 'preguntas'
  get 'preguntas/nuevo', to: 'preguntas#nuevo', as: 'nuevo_pregunta'
  get 'preguntas/:id', to: 'preguntas#mostrar', as: 'pregunta'
  get 'preguntas/:id/editar', to: 'preguntas#editar', as: 'editar_pregunta'
  post 'preguntas' , to: 'preguntas#crear', as: 'nueva_pregunta'
  put 'preguntas/:id' ,to: 'preguntas#update'
  patch 'preguntas/:id' , to: 'preguntas#update'
  delete 'preguntas/:id' , to: 'preguntas#eliminar'


  get 'informes/', to: 'informes#index', as: 'informes'
  get 'informes/nuevo', to: 'informes#nuevo', as: 'nuevo_informe'
  get 'informes/:id',to: 'informes#mostrar', as: 'informe'
  get 'informes/:id/editar', to: 'informes#editar', as: 'editar_informe'
  post 'informes', to: 'informes#crear'
  put 'informes/:id' , to: 'informes#update'
  patch 'informes/:id' ,to: 'informes#update'
  delete 'informes/:id', to: 'informes#eliminar'



  get 'estudiantes/', to: 'estudiantes#index', as: 'estudiantes'
  get 'estudiantes/nuevo/', to: 'estudiantes#nuevo', as: 'nuevo_estudiante'
  get 'estudiantes/:id/asignaturas', to: 'estudiantes#mostrarasignatura', as: 'asignaturas_estudiantes'
  get 'estudiantes/:id',to: 'estudiantes#mostrar', as: 'estudiante'
  get 'estudiantes/:id/editar', to: 'estudiantes#editar', as: 'editar_estudiante'
  post 'estudiantes/', to: 'estudiantes#crear'
  put 'estudiantes/:id' , to: 'estudiantes#update'
  patch 'estudiantes/:id' ,to: 'estudiantes#update'
  delete 'estudiantes/:id', to: 'estudiantes#eliminar'

  get 'preguntainforme/', to: 'pregunta_informes#index', as: 'pregunta_informes'
  get 'preguntainforme/nuevo/:id/pregunta', to: 'pregunta_informes#nuevo', as: 'nuevo_informe_pregunta'
  get 'preguntainforme/:id',to: 'pregunta_informes#mostrar', as: 'pregunta_informe'
  #get 'preguntainforme/:id/editar', to: 'pregunta_informes#editar', as: 'editar_pregunta_informe'
  post 'preguntainforme', to: 'pregunta_informes#crear', as: 'crear_informe_nuevo'
  put 'preguntainforme/:id' , to: 'pregunta_informes#update'
  patch 'preguntainforme/:id' ,to: 'pregunta_informes#update'
  delete 'preguntainforme/:id', to: 'pregunta_informes#eliminar'

  #get 'grupotutores/', to: 'estudiantes#tutores', as: 'tutores'
  get 'grupotutores/', to: 'grupo_tutores#index', as: 'tutores'
  get 'grupotutores/nuevo/', to: 'grupo_tutores#nuevo', as: 'nuevo_grupo_tutor'
  get 'grupotutores/:id',to: 'grupo_tutores#mostrar', as: 'tutore'
  get 'grupotutores/:id/editar', to: 'grupo_tutores#editar', as: 'editar_grupo_tutor'
  post 'grupotutores/', to: 'grupo_tutores#crear'
  put 'grupotutores/:id' , to: 'grupo_tutores#update'
  patch 'grupotutores/:id' ,to: 'grupo_tutores#update'
  delete 'grupotutores/:id', to: 'grupo_tutores#eliminar'

  get 'grupotutorados/', to: 'estudiantes#tutorados', as: 'tutorados'

  get 'grupotutorados/', to: 'grupo_tutorados#index', as: 'grupo_tutorados_index'
  get 'grupotutores/:id/tutorados/nuevo/', to: 'grupo_tutorados#nuevo', as: 'nuevo_grupo_tutorado'
  get 'grupotutorados/:id',to: 'grupo_tutorados#mostrar', as: 'grupo_tutorado'
  #get 'grupotutorados/:id/editar', to: 'grupo_tutorados#editar', as: 'editar_grupo_tutorado'
  post 'grupotutorados', to: 'grupo_tutorados#crear', as: 'agregar_tutorado_grupo'
  put 'grupotutorados/:id' , to: 'grupo_tutorados#update'
  patch 'grupotutorados/:id' ,to: 'grupo_tutorados#update'
  delete 'grupotutorados/:id', to: 'grupo_tutorados#eliminar'








end

app/controllers/grupo_tutores_controller.rb
class GrupoTutoresController < ApplicationController


  def index
    @estudiantes = Estudiante.where(rol_id: Rol.find_by_nombres('Tutor'))
  end

  def nuevo
    @grupo_tutores = GrupoTutor.new
  end

  def crear
    estudiante_id=  params()[:nuevo_grupo_tutor][:estudiante_id] # Tutor
    grupo_tutorado = GrupoTutor.create(estudiante_id: estudiante_id)
    respond_to do |format|
      format.html{redirect_to nuevo_grupo_tutorado_path(grupo_tutorado.id), notice: 'Grupo creado'}
    end

  end

  def mostrar
    estudiante_id = params[:id]

     @estudiante = Estudiante.find(estudiante_id)


  end

  def editar
    @grupo_tutores = GrupoTutor.find(params[:id])
  end

  def eliminar
    @grupo_tutores.destroy(grupo_tutores_params)
    respond_to do |format|
      format.html {redirect_to @grupo_tutores, notice:'Se ha eliminado el grupo'}
    end
  end

  def update
    respond_to do |format|
      if @grupo_tutores.update(estudiante_params)
        format.html {redirect_to @grupo_tutores, notice:'Se ha editado el grupo'}
      else
        format.html {render :editar}
      end
    end
  end


  private
  def set_grupo_tutores
    @grupo_tutores = GrupoTutor.find(params[:id])
  end

  def grupo_tutores_params
    params.require(:grupo_tutor).permit(:estudiante_id,
                                        grupo_tutorados_attributes: [:id, :estudiante_id, :grupo_tutor_id, :done, :_destroy])
  end

end

app/helpers/grupo_tutores_helper.rb
module GrupoTutoresHelper
end

app/views/grupo_tutores/_form.html.erb
<%= simple_form_for @grupo_tutores, url: grupotutores_url, as: 'nuevo_grupo_tutor'  do |f| %>
    <%= f.error_notification %>


    <p>
    <%= f.label :grupo_tutor %><br>
    <%= f.select('estudiante_id', Estudiante.where(rol_id: (Rol.find_by_nombres('Tutor')).id).collect {|c| [c.nombres, c.id]}, { include_blank: false }, {class: 'chosen-select'}) %>
    </p>


    <%= f.button :submit, "Guardar", class: "my-button" %>




    <% end %>

app/views/grupo_tutores/_tutorados.html.erb
<% @grupo_tutorados  = GrupoTutorado.new  %>
<%= simple_form_for @grupo_tutorados, url: nuevo_grupo_tutor_url, as: 'nuevo_grupo_tutor'  do |f| %>
    <%= f.error_notification %>

    <p>
      <%= f.label :tutorados %><br>
      <%= f.select('grupo_tutor_id', Estudiante.where(rol_id: (Rol.find_by_nombres('Tutorado')).id).collect {|c| [c.nombres, c.id]}, { include_blank: false }, {class: 'chosen-select'}) %>
    </p>


<% end %>

app/views/grupo_tutores/editar.html.erb
<h1>Editar Grupo</h1>
<%=render 'form'%>
<%= link_to 'Volver', root_path, class:'btn btn-info' %><br>

app/views/grupo_tutores/index.html.erb
<h3> <%= link_to 'Crear grupo tutor', nuevo_grupo_tutor_path, class:'btn btn-primary btn-md' %> </h3>

<table class="table">
  <thead>
  <tr>
    <th>Nombres Tutores</th>
    <th>Apellidos</th>
    <th>Mostrar</th>
    <th>Informe Asignado</th>

  </tr>
  </thead>
  <tbody>

  <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.nombres %></td>
        <td><%= estudiante.apellidos %></td>

        <td><%= link_to 'Mostrar', tutore_path(estudiante),class: 'btn btn-info' %></td>
        <td><%= link_to 'Informe', informe_path(estudiante),class: 'btn btn-info' %> </td>

      </tr>
  <% end %>
  </tbody>

</table>

app/views/grupo_tutores/mostrar.html.erb
<h1>Grupos de : <%= @estudiante.nombres %></h1>
<% if @estudiante.grupo_tutors.size > 0 %>
    <p><strong><%= 'Numero de grupo historico : ' + @estudiante.grupo_tutors.size.to_s%></strong></p> <br>
    <% @estudiante.grupo_tutors.each do |actual| %>

        <%= link_to actual.created_at.strftime("%m-%Y") ,grupo_tutorado_url(actual.id) , class:'btn btn-primary btn-md' %>

    <% end %>
<% else %>
    <p>No tiene grupo </p>
<% end %> <br><br>

<%= link_to 'Volver', grupotutores_url, class: 'btn btn-info' %>

app/views/grupo_tutores/nuevo.html.erb
<h1>Nuevo grupo </h1>
<%= render 'form' %>

<%= link_to 'Volver', root_path, class:'btn btn-info' %><br>