config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
      sessions: 'admins/sessions'
  }


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'inicio#index'
  get 'inicio', to: 'inicio#index', as:'inicio'

  get 'informeestudiante/', to: 'informe_estudiantes#index', as: 'informeestudiantes'
  get 'informeestudiante/nuevo/', to: 'informe_estudiantes#nuevo', as: 'nuevo_informe_estudiante'
  #get 'informeestudiante/:id',to: 'informe_estudiantes#mostrar', as: 'informeestudiante'

  get 'informeestudiante/:id/estudiante',to: 'informe_estudiantes#informes_por_estudiante', as: 'informeporestudiante'

  get 'informeestudiante/:id/editar', to: 'informe_estudiantes#editar', as: 'editar_informe_estudiante'
  post 'informeestudiante/', to: 'informe_estudiantes#crear', as: 'agregar_informe_estudiante'
  put 'informeestudiante/:id' , to: 'informe_estudiantes#update'
  patch 'informeestudiante/:id' ,to: 'informe_estudiantes#update'
  delete 'informeestudiante/:id', to: 'informe_estudiantes#eliminar'



  get 'preguntas/', to: 'preguntas#index', as: 'preguntas'
  get 'preguntas/nuevo', to: 'preguntas#nuevo', as: 'nuevo_pregunta'
  get 'preguntas/:id', to: 'preguntas#mostrar', as: 'pregunta'
  get 'preguntas/:id/editar', to: 'preguntas#editar', as: 'editar_pregunta'
  post 'preguntas' , to: 'preguntas#crear', as: 'nueva_pregunta'
  put 'preguntas/:id' ,to: 'preguntas#update'
  patch 'preguntas/:id' , to: 'preguntas#update'
  delete 'preguntas/:id' , to: 'preguntas#eliminar'


  get 'informes/', to: 'informes#index', as: 'informes'
  get 'informes/nuevo', to: 'informes#nuevo', as: 'nuevo_informe'
  get 'informes/:id',to: 'informes#mostrar', as: 'informe'
  get 'informes/:id/editar', to: 'informes#editar', as: 'editar_informe'
  post 'informes', to: 'informes#crear'
  put 'informes/:id' , to: 'informes#update'
  patch 'informes/:id' ,to: 'informes#update'
  delete 'informes/:id', to: 'informes#eliminar'



  get 'estudiantes/', to: 'estudiantes#index', as: 'estudiantes'
  get 'estudiantes/nuevo/', to: 'estudiantes#nuevo', as: 'nuevo_estudiante'
  get 'estudiantes/:id/asignaturas', to: 'estudiantes#mostrarasignatura', as: 'asignaturas_estudiantes'
  get 'estudiantes/:id',to: 'estudiantes#mostrar', as: 'estudiante'
  get 'estudiantes/:id/editar', to: 'estudiantes#editar', as: 'editar_estudiante'
  post 'estudiantes/', to: 'estudiantes#crear'
  put 'estudiantes/:id' , to: 'estudiantes#update'
  patch 'estudiantes/:id' ,to: 'estudiantes#update'
  delete 'estudiantes/:id', to: 'estudiantes#eliminar'

  get 'preguntainforme/', to: 'pregunta_informes#index', as: 'pregunta_informes'
  get 'preguntainforme/nuevo/:id/pregunta', to: 'pregunta_informes#nuevo', as: 'nuevo_informe_pregunta'
  get 'preguntainforme/:id',to: 'pregunta_informes#mostrar', as: 'pregunta_informe'
  #get 'preguntainforme/:id/editar', to: 'pregunta_informes#editar', as: 'editar_pregunta_informe'
  post 'preguntainforme', to: 'pregunta_informes#crear', as: 'crear_informe_nuevo'
  put 'preguntainforme/:id' , to: 'pregunta_informes#update'
  patch 'preguntainforme/:id' ,to: 'pregunta_informes#update'
  delete 'preguntainforme/:id', to: 'pregunta_informes#eliminar'

  #get 'grupotutores/', to: 'estudiantes#tutores', as: 'tutores'
  get 'grupotutores/', to: 'grupo_tutores#index', as: 'tutores'
  get 'grupotutores/nuevo/', to: 'grupo_tutores#nuevo', as: 'nuevo_grupo_tutor'
  get 'grupotutores/:id',to: 'grupo_tutores#mostrar', as: 'tutore'
  get 'grupotutores/:id/editar', to: 'grupo_tutores#editar', as: 'editar_grupo_tutor'
  post 'grupotutores/', to: 'grupo_tutores#crear'
  put 'grupotutores/:id' , to: 'grupo_tutores#update'
  patch 'grupotutores/:id' ,to: 'grupo_tutores#update'
  delete 'grupotutores/:id', to: 'grupo_tutores#eliminar'

  get 'grupotutorados/', to: 'estudiantes#tutorados', as: 'tutorados'

  get 'grupotutorados/', to: 'grupo_tutorados#index', as: 'grupo_tutorados_index'
  get 'grupotutores/:id/tutorados/nuevo/', to: 'grupo_tutorados#nuevo', as: 'nuevo_grupo_tutorado'
  get 'grupotutorados/:id',to: 'grupo_tutorados#mostrar', as: 'grupo_tutorado'
  #get 'grupotutorados/:id/editar', to: 'grupo_tutorados#editar', as: 'editar_grupo_tutorado'
  post 'grupotutorados', to: 'grupo_tutorados#crear', as: 'agregar_tutorado_grupo'
  put 'grupotutorados/:id' , to: 'grupo_tutorados#update'
  patch 'grupotutorados/:id' ,to: 'grupo_tutorados#update'
  delete 'grupotutorados/:id', to: 'grupo_tutorados#eliminar'








end

app/models/estudiante.rb
class Estudiante < ApplicationRecord

  has_many :informes
  has_many :asignatura_cursadas
  belongs_to :rol
  has_many :grupo_tutors
  has_many :grupo_tutorados
  has_many :informe_estudiantes
  belongs_to :carrera
  belongs_to :priorizacion
  belongs_to :comuna

  validates :apellidos, presence: true
  validates :direccion, presence: true
  validates :email, uniqueness: true

  validates :rut, uniqueness: true, rut:true

  validates :nombres, presence: {:message => "LLenado Obligatorio"}
  validates :apellidos, presence: {:message => "LLenado Obligatorio"}

end

app/controllers/estudiantes_controller.rb
require 'sepa_api'

class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:mostrar, :editar, :eliminar, :update, :mostrarasignatura]
  before_action :authenticate_admin!

  def index
    @index = 'index'
    @estudiantes = Estudiante.paginate(:page => params[:page], :per_page => 12)
  end

  def crear
    rut = params['estudiante']['rut']
    sepa = SepaApi.new()
    @estudiante = sepa.getEstudiante(rut)
    @estudiante.rol_id = (Rol.find_by_nombres('Tutorado')).id
    @estudiante.priorizacion_id = (Priorizacion.find_by_nombre('No priorizado')).id
    if @estudiante != nil
      if Estudiante.find_by_rut(@estudiante.rut) == nil
        respond_to do |format|
          if @estudiante.save
            format.html {redirect_to estudiante_path(@estudiante), notice: 'Guardado exitosamente en base de datos'}
          else
            format.html {render :nuevo}
          end
        end
      else
        respond_to do |format|
          @estudiante = Estudiante.find_by_rut(@estudiante.rut)
          format.html {redirect_to estudiante_path(@estudiante), notice: 'Ya existe dicho estudiante'}
        end
      end
    else
      respond_to do |format|
        format.html {redirect_to nuevo_estudiante_path(@estudiante), notice: 'Estudiante no encontrado en dirdoc'}
      end
    end
  end

  def mostrar
    @estudiante = Estudiante.find(params[:id])
  end

  def editar
    @estudiante = Estudiante.find(params[:id])
  end

  def eliminar
    @estudiante.destroy
    respond_to do |format|
      format.html {redirect_to @estudiante, notice: 'Se ha eliminado al estudiante'}
    end
  end

  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html {redirect_to @estudiante, notice: 'Se ha editado el estudiante'}
      else
        format.html {render :editar}
      end
    end
  end

  def nuevo
    @estudiante = Estudiante.new
  end

  def tutores
    @index = 'no index'
    @estudiantes = Estudiante.where(rol_id: (Rol.find_by_nombres('Tutor')).id).paginate(:page => params[:page], :per_page => 12)
    respond_to do |format|
      format.html {render :template => "/estudiantes/index"}
    end
  end

  def tutorados
    @index = 'index'
    @estudiantes = Estudiante.where(rol_id: (Rol.find_by_nombres('Tutorado')).id).paginate(:page => params[:page], :per_page => 12)
    respond_to do |format|
      format.html {render :template => "/estudiantes/index"}
    end
  end

  def mostrarasignatura

    sepa = SepaApi.new()

    sepa.asignaturasUltimoSemestre(@estudiante.rut)

    @estudiante

  end

  private
  def set_estudiante
    @estudiante = Estudiante.find(params[:id])
  end

  def estudiante_params
    params.require(:estudiante).permit(:rut, :nombres, :apellidos, :email, :direccion, :priorizacion_id, :rol_id, :comuna_id, :carrera_id, :fecha_nacimiento, :edad)
  end


end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_form.html.erb
<%= simple_form_for(@estudiante, :html => {:role => 'form'}) do |f| %>
    <% if @estudiante.errors.any? %>
        <%= pluralize(@estudiante.errors.count, "error") %>

        <% @estudiante.errors.full_messages.each do |actual| %>
            <%= actual %>
        <% end %>
    <% end %>
    <p>
      <%= f.label :nombres %> <br>
      <%= f.text_field :nombres %>
    </p>
    <p>
      <%= f.label :apellidos %> <br>
      <%= f.text_field :apellidos %>
    </p>
    <p>
      <%= f.label :rut %> <br>
      <%= f.text_field :rut %>
    </p>
    <p>
      <%= f.label :email %> <br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :direccion %> <br>
      <%= f.text_field :direccion %>
    </p>
    <p>
      <%= f.label :ingreso%> <br>
      <%= f.text_field :ingreso%>
    </p>
    <div class="field">
      <%= f.input :edad, collection: 17..60, prompt: "Selecciona Edad", selected: 17 %>
    </div>


    <p>
      <%= f.label :fecha_nacimiento%> <br>
      <%= f.date_field :fecha_nacimiento%>
    </p>
     <p>
       <%= f.label :priorizacion %><br>
       <%= f.select('priorizacion_id', Priorizacion.all.collect { |c| [c.nombre, c.id] }) %>

     </p>
    <p>
      <%= f.label :comuna %><br>
      <%= f.select('comuna_id', Comuna.all.collect { |c| [c.nombre, c.id] }) %>
    </p>
    <p>
      <%= f.label :rol %><br>
      <%= f.select('rol_id', Rol.all.collect { |c| [c.nombres, c.id] }) %>
    </p>


    <%= f.button :submit, "Actualizar", class: "my-button" %>
<% end %>

app/views/estudiantes/crear.html.erb
<h1>Ingresa un nuevo estudiante</h1>

<%= render 'form' %> <br>

<%= link_to 'Volver', estudiantes_path, class: 'btn btn-info' %><br>

app/views/estudiantes/editar.html.erb
<h1>Editar</h1>
<%=render 'form'%> <br>
<%= link_to 'Volver', estudiantes_path, class: 'btn btn-info' %><br>

app/views/estudiantes/index.html.erb
<div class = "row">
    <div class="col-sm-4"><h3> <%= link_to 'Crear estudiante', nuevo_estudiante_path, class:'btn btn-primary btn-md' %> </h3>
    </div>

</div>




<table class="table">
  <thead>
  <tr>
    <th>Nombres</th>
    <th>Apellidos</th>
    <th>Priorizacion</th>
    <th>Mostrar</th>
    <th>Editar</th>
    <th>Asignaturas</th>
  </tr>
  </thead>
  <tbody>
  <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.nombres %></td>
        <td><%= estudiante.apellidos %></td>
        <td>
          <% if estudiante.priorizacion !=nil %>
              <%= estudiante.priorizacion.nombre.to_s %>
          <% end %>
        </td>
        <td><%= link_to 'Mostrar', estudiante_url(estudiante),class: 'btn btn-info' %></td>
        <td><%= link_to 'Editar', editar_estudiante_path(estudiante),class: 'btn btn-info' %></td>
        <td><%= link_to 'Asignatura', asignaturas_estudiantes_path(estudiante),class: 'btn btn-info' %></td>
      </tr>
  <% end %>

  </tbody>

</table>

<%= will_paginate @estudiantes, renderer: BootstrapPagination::Rails %>

app/views/estudiantes/mostrar.html.erb
<h1>
  <%= @estudiante.nombres.to_s.upcase %>
  <% if @estudiante.priorizacion==nil || @estudiante.priorizacion.nombre == 'No priorizado' %>
      <% if @estudiante.rol!=nil %>
          <% if @estudiante.rol.nombres != 'Tutor' %>
              <br><span class="label label-danger">Estudiante no Priorizado</span>
          <% end %>
      <% end %>
  <% end %>
</h1>

<table class="table table-bordered table-striped">
  <tbody>
  <tr>
    <td>Nombres</td>
    <td><%= @estudiante.nombres.to_s %></td>
  </tr>
  <tr>
    <td>Apellidos</td>
    <td><%= @estudiante.apellidos.to_s %></td>
  </tr>
  <tr>
    <td>Rut</td>
    <td><%= @estudiante.rut.to_s %></td>
  </tr>
  <tr>
    <td>E-mail</td>
    <td><%= @estudiante.email.to_s %></td>
  </tr>
  <tr>
    <td>Dirección</td>
    <td><%= @estudiante.direccion.to_s %></td>
  </tr>
  <tr>
    <td>Comuna</td>
    <td><%= @estudiante.comuna.nombre.to_s %></td>
  </tr>
  <tr>
    <td>Rol</td>
    <% if @estudiante.rol!=nil %>
        <td><%= @estudiante.rol.nombres.to_s %></td>
    <% else %>
        <td> Estudiante sin rol</td>
    <% end %>
  </tr>
  <tr>
    <td>Carrera</td>
    <td><%= @estudiante.carrera.nombre.to_s %></td>
  </tr>
  <tr>
    <td>Priorizacion</td>
    <% if @estudiante.priorizacion!=nil %>
        <td><%= @estudiante.priorizacion.nombre.to_s %></td>
    <% else %>
        <td>No Priorizado</td>
    <% end %>
  </tr>
  <tr>
    <td>Fecha Nacimiento</td>
    <% if @estudiante.fecha_nacimiento!=nil %>
    <td><%= @estudiante.fecha_nacimiento.strftime("%d - %m - %Y") %></td>
    <% else %>
        <td>No hay fecha</td>
    <% end %>
  </tr>
  <tr>
    <td>Edad</td>
    <td><%= @estudiante.edad.to_s %></td>
  </tr>
  <tr>
    <td>Nº de Ingresos</td>
    <td><%= @estudiante.ingreso.to_s %></td>
  </tr>
  </tbody>
</table>

<%= link_to 'Volver', estudiantes_path, class: 'btn btn-info' %><br>

app/views/estudiantes/mostrarasignatura.html.erb
<h1>Estudiante: <%= @estudiante.nombres %>

  <% if @estudiante.asignatura_cursadas.size ==0 %>
      <br><span class="label label-danger">Estudiante no ha cursado su primer semestre</span>
  <% else %>
      Asignaturas del Año: <%= @estudiante.asignatura_cursadas[-1].anio %><br>
      Semestre n°:<%= @estudiante.asignatura_cursadas[0].semestre %><br>
  <% end %>

</h1>
<table class="table">
  <thead>
  <tr>
    <th>Asignatura</th>
    <th>Nota</th>
    <th>Estado</th>
  </tr>
  </thead>

  <tbody>
  <% @estudiante.asignatura_cursadas.each do |asignatura| %>
      <tr>
        <td><%= asignatura.asignatura.nombre %></td>
        <td><%= asignatura.nota %></td>
        <td>
          <% if asignatura.nota >= 4.0 %>
              <dt>
              <p class="text-success">APROBADO</p></dt>
          <% end %>
          <% if asignatura.nota <= 3.9 %>
              <dt>
              <p class="text-warning">REPROBADO</p></dt>
          <% end %>
        </td>

      </tr>
  <% end %>

  </tbody>
</table>
<%= link_to 'Volver', estudiantes_path, class: 'btn btn-info' %><br>

app/views/estudiantes/nuevo.html.erb
<h1>Ingresa un estudiante</h1>

<%= form_for(@estudiante, :html => {:role => 'form'}) do |f| %>
    <% if @estudiante.errors.any? %>
        <%= pluralize(@estudiante.errors.count, "error") %>

        <% @estudiante.errors.full_messages.each do |actual| %>
            <%= actual %>
        <% end %>
    <% end %>

    <p>
      <%= f.label :rut %> <br>
      <%= f.text_field :rut %>
    </p>


    <%= f.submit %> <br>
<% end %> <br>

<%= link_to 'Volver', estudiantes_path, class: 'btn btn-info' %><br>